### ISSUE TITLE
2.2.1 Issues

### ISSUE THREAD

**Issue by joesixpack** [Optiminer/OptiminerEquihash#28]
Mining seems to get progressively slower over very long periods of time.  It is subtle.

Another annoyance is CTRL C won't quit the mining without locking up the system, requiring a hard reboot.

**Comment by Optiminer** [comment]
Please provide the information as requested on 
https://github.com/Optiminer/OptiminerEquihash/blob/master/reportbug.md

If mining gets slower over time this is probably because the GPUs are throttling because they are too hot. CTRL-C normally quits the miner. There must be some problem with your system setup.
